%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/nitsch/ros2-triple_ws/imu_static_data.csv
%
% Auto-generated by MATLAB on 31-Jan-2024 07:36:14

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["accX", "accY", "accZ", "gyroX", "gyroY", "gyroZ"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("../../../imu_static_data.csv", opts);

%% Convert to output type
accX = tbl.accX;
accY = tbl.accY;
accZ = tbl.accZ;
gyroX = tbl.gyroX;
gyroY = tbl.gyroY;
gyroZ = tbl.gyroZ;

%% Clear temporary variables
clear opts tbl
